export const SITE_NAME = 'Wearix';
export const SITE_TAGLINE = 'Wear Your Style';
const rawSiteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://wearix.com.bd';
export const SITE_URL = rawSiteUrl.startsWith('http') ? rawSiteUrl : `https://${rawSiteUrl}`;
export const WHATSAPP_NUMBER = '+8801700000000';

export const CATEGORIES = [
  { name: 'Men', slug: 'men', icon: 'User', image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400&q=80' },
  { name: 'Women', slug: 'women', icon: 'UserCircle', image: 'https://images.unsplash.com/photo-1574180566232-aaad1b5b8450?w=400&q=80' },
  { name: 'Kids', slug: 'kids', icon: 'Baby', image: 'https://images.unsplash.com/photo-1519238263530-99abad67b8d4?w=400&q=80' },
  { name: 'Teens', slug: 'teens', icon: 'Smile', image: 'https://images.unsplash.com/photo-1517423568366-8b83523034fd?w=400&q=80' },
  { name: 'T-Shirts', slug: 't-shirts', icon: 'Shirt', image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&q=80' },
  { name: 'Jerseys', slug: 'jersey', icon: 'Dribbble', image: 'https://images.unsplash.com/photo-1622519407650-3df9883f76a5?w=400&q=80' },
  { name: 'Panjabi', slug: 'panjabi', icon: 'Star', image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e4?w=400&q=80' },
  { name: 'Hoodies', slug: 'hoodies', icon: 'Snowflake', image: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400&q=80' },
  { name: 'Polos', slug: 'polos', icon: 'Briefcase', image: 'https://images.unsplash.com/photo-1625910513961-c3c22e0d1432?w=400&q=80' },
  { name: 'Pants', slug: 'pants', icon: 'Scissors', image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=400&q=80' },
  { name: 'Accessories', slug: 'accessories', icon: 'Watch', image: 'https://images.unsplash.com/photo-1523206489230-c012c64b2b48?w=400&q=80' },
];

export const SIZES_GENERAL = ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL'];
export const SIZES_KIDS = ['2Y', '4Y', '6Y', '8Y', '10Y', '12Y', '14Y'];
export const SIZES_PANTS = ['28', '30', '32', '34', '36', '38', '40'];

export const DIVISIONS = [
  'Dhaka', 'Chittagong', 'Sylhet', 'Rajshahi',
  'Khulna', 'Barishal', 'Mymensingh', 'Rangpur',
];

export const SHIPPING_FEE = {
  inside_dhaka: 60,
  outside_dhaka: 120,
};

export const PAYMENT_METHODS = [
  { id: 'bkash', label: 'bKash', color: '#E2136E', description: 'Pay with bKash mobile banking' },
  { id: 'nagad', label: 'Nagad', color: '#F6891F', description: 'Pay with Nagad mobile banking' },
  { id: 'sslcommerz', label: 'Card / Net Banking', color: '#2563EB', description: 'Visa, Mastercard, DBBL, etc.' },
  { id: 'cod', label: 'Cash on Delivery', color: '#16A34A', description: 'Pay when you receive the parcel' },
];

export const DEMO_PRODUCTS = [
  {
    id: '1',
    name: 'Premium Cotton Oxford Shirt',
    slug: 'premium-cotton-oxford-shirt',
    description: 'A beautifully crafted Oxford shirt made from 100% premium Bangladeshi cotton. Perfect for office wear or casual outings.',
    category: 'shirts',
    gender: 'men' as const,
    price: 1200,
    discountPrice: 990,
    images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Sky Blue', 'Navy'],
    stock: { S: 10, M: 15, L: 8, XL: 5, XXL: 3 },
    tags: ['shirt', 'cotton', 'office', 'men'],
    rating: 4.5,
    reviewCount: 128,
    isFeatured: true,
    isActive: true,
    createdAt: '2024-01-01',
  },
  {
    id: '2',
    name: 'Oversized Graphic Tee',
    slug: 'oversized-graphic-tee',
    description: 'Relaxed fit graphic tee with unique Bangladeshi street art print. Ultra-soft 180 GSM jersey cotton.',
    category: 't-shirts',
    gender: 'unisex' as const,
    price: 650,
    discountPrice: 499,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Olive'],
    stock: { S: 20, M: 25, L: 30, XL: 20, XXL: 10 },
    tags: ['t-shirt', 'graphic', 'oversized', 'unisex'],
    rating: 4.7,
    reviewCount: 256,
    isFeatured: true,
    isActive: true,
    createdAt: '2024-01-02',
  },
  {
    id: '3',
    name: 'Bangladesh Cricket Jersey',
    slug: 'bangladesh-cricket-jersey',
    description: 'Official-style Bangladesh cricket jersey with moisture-wicking fabric. Feel like a tiger on the field!',
    category: 'jersey',
    gender: 'men' as const,
    price: 850,
    images: ['https://images.unsplash.com/photo-1622519407650-3df9883f76a5?w=800'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Green'],
    stock: { S: 15, M: 20, L: 25, XL: 15, XXL: 8 },
    tags: ['jersey', 'cricket', 'bangladesh', 'sport'],
    rating: 4.8,
    reviewCount: 389,
    isFeatured: true,
    isActive: true,
    createdAt: '2024-01-03',
  },
  {
    id: '4',
    name: 'Eid Special Embroidered Panjabi',
    slug: 'eid-special-embroidered-panjabi',
    description: 'Premium Eid collection panjabi with intricate embroidery work. Made from soft cotton voile fabric.',
    category: 'panjabi',
    gender: 'men' as const,
    price: 2500,
    discountPrice: 1999,
    images: ['https://images.unsplash.com/photo-1583391733956-6c78276477e4?w=800'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Cream', 'Light Blue'],
    stock: { S: 5, M: 8, L: 10, XL: 7, XXL: 3 },
    tags: ['panjabi', 'eid', 'embroidery', 'traditional'],
    rating: 4.9,
    reviewCount: 72,
    isFeatured: true,
    isActive: true,
    createdAt: '2024-01-04',
  },
  {
    id: '5',
    name: 'Fleece Pullover Hoodie',
    slug: 'fleece-pullover-hoodie',
    description: 'Cozy 320 GSM fleece hoodie for the winter season. Unisex fit, roomy kangaroo pocket.',
    category: 'hoodies',
    gender: 'unisex' as const,
    price: 1450,
    discountPrice: 1199,
    images: ['https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Charcoal', 'Maroon'],
    stock: { S: 12, M: 18, L: 22, XL: 14, XXL: 7 },
    tags: ['hoodie', 'winter', 'fleece', 'unisex'],
    rating: 4.6,
    reviewCount: 184,
    isFeatured: true,
    isActive: true,
    createdAt: '2024-01-05',
  },
  {
    id: '6',
    name: 'Classic Polo Shirt',
    slug: 'classic-polo-shirt',
    description: 'Timeless polo shirt in breathable pique cotton. The perfect smart-casual staple for Dhaka weather.',
    category: 'polos',
    gender: 'men' as const,
    price: 750,
    discountPrice: 649,
    images: ['https://images.unsplash.com/photo-1625910513961-c3c22e0d1432?w=800'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy', 'White', 'Red', 'Green'],
    stock: { S: 18, M: 24, L: 30, XL: 20, XXL: 10 },
    tags: ['polo', 'smart-casual', 'cotton', 'men'],
    rating: 4.4,
    reviewCount: 211,
    isFeatured: false,
    isActive: true,
    createdAt: '2024-01-06',
  },
  {
    id: '7',
    name: 'Women Floral Kurti',
    slug: 'women-floral-kurti',
    description: 'Beautiful floral print kurti in soft rayon fabric. Comfortable and stylish for daily wear.',
    category: 'women',
    gender: 'women' as const,
    price: 899,
    discountPrice: 749,
    images: ['https://images.unsplash.com/photo-1574180566232-aaad1b5b8450?w=800'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Pink Floral', 'Blue Floral', 'Yellow Floral'],
    stock: { XS: 8, S: 12, M: 16, L: 10, XL: 5 },
    tags: ['kurti', 'women', 'floral', 'daily-wear'],
    rating: 4.7,
    reviewCount: 143,
    isFeatured: true,
    isActive: true,
    createdAt: '2024-01-07',
  },
  {
    id: '8',
    name: 'Slim Fit Chino Trousers',
    slug: 'slim-fit-chino-trousers',
    description: 'Versatile slim-fit chinos that work for both office and weekend. Stretch cotton blend for comfort.',
    category: 'pants',
    gender: 'men' as const,
    price: 1100,
    discountPrice: 949,
    images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800'],
    sizes: ['28', '30', '32', '34', '36', '38'],
    colors: ['Khaki', 'Navy', 'Olive', 'Black'],
    stock: { '28': 8, '30': 15, '32': 20, '34': 18, '36': 12, '38': 6 },
    tags: ['pants', 'chino', 'slim-fit', 'office'],
    rating: 4.5,
    reviewCount: 97,
    isFeatured: false,
    isActive: true,
    createdAt: '2024-01-08',
  },
];
